[workspace]
resolver = "1"
members = [
  # library projects
  "lsp-positions",
  "stack-graphs",
  "tree-sitter-stack-graphs",
  "languages/*",
]
default-members = [
  "lsp-positions",
  "stack-graphs",
  "tree-sitter-stack-graphs",
]
